# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/data_viz',
                'doc_host': 'https://MeherKharbachi.github.io',
                'git_url': 'https://github.com/MeherKharbachi/data_viz',
                'lib_path': 'data_viz'},
  'syms': {'data_viz.fminside_vs_fifa': {}}}
