# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_fminside_vs_fifa.ipynb.

# %% auto 0
__all__ = ['df_fm', 'df_fifa', 'df_stats']

# %% ../nbs/00_fminside_vs_fifa.ipynb 3
import pandas as pd
from pivottablejs import pivot_ui

# %% ../nbs/00_fminside_vs_fifa.ipynb 5
# fminside data
df_fm = pd.read_csv("pl_fm_stats.csv")
df_fm["data"] = "Fminside"

# %% ../nbs/00_fminside_vs_fifa.ipynb 7
# fifa data
df_fifa = pd.read_csv("pl_fifa_stats.csv")
df_fifa["data"] = "Fifa"

# %% ../nbs/00_fminside_vs_fifa.ipynb 9
df_stats = pd.concat([df_fm, df_fifa])

# %% ../nbs/00_fminside_vs_fifa.ipynb 11
pivot_ui(df_stats)
